# Generated by Django 3.1.6 on 2024-07-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Note',
        ),
    ]
